/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as AuthLayoutImport } from './routes/_auth-layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as AuthLayoutLoginImport } from './routes/_auth-layout/login'
import { Route as LayoutContactIndexImport } from './routes/_layout/contact/index'
import { Route as LayoutAboutIndexImport } from './routes/_layout/about/index'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const AuthLayoutRoute = AuthLayoutImport.update({
  id: '/_auth-layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const AuthLayoutLoginRoute = AuthLayoutLoginImport.update({
  path: '/login',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const LayoutContactIndexRoute = LayoutContactIndexImport.update({
  path: '/contact/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAboutIndexRoute = LayoutAboutIndexImport.update({
  path: '/about/',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth-layout': {
      id: '/_auth-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_auth-layout/login': {
      id: '/_auth-layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLayoutLoginImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/about/': {
      id: '/_layout/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/contact/': {
      id: '/_layout/contact/'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof LayoutContactIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  AuthLayoutRoute: AuthLayoutRoute.addChildren({ AuthLayoutLoginRoute }),
  LayoutRoute: LayoutRoute.addChildren({
    LayoutIndexRoute,
    LayoutAboutIndexRoute,
    LayoutContactIndexRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth-layout",
        "/_layout"
      ]
    },
    "/_auth-layout": {
      "filePath": "_auth-layout.tsx",
      "children": [
        "/_auth-layout/login"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/",
        "/_layout/about/",
        "/_layout/contact/"
      ]
    },
    "/_auth-layout/login": {
      "filePath": "_auth-layout/login.tsx",
      "parent": "/_auth-layout"
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/about/": {
      "filePath": "_layout/about/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/contact/": {
      "filePath": "_layout/contact/index.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
